-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Total Maximum Energy Shield granted {0:+d}"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Grants Allies {0:+d} to their Total Maximum Energy Shield"
			}
		},
		stats={
			[1]="discipline_grant_allies_total_maximum_energy_shield_+"
		}
	},
	["discipline_grant_allies_total_maximum_energy_shield_+"]=1,
	parent="skill_stat_descriptions"
}