-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Damage Gained from Ground Surfaces {0}%"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Gains {0}% of damage as the corresponding Type when\npassing over a Ground Surface"
			}
		},
		stats={
			[1]="eye_of_winter_damage_+%_final_per_ground_effect_type"
		}
	},
	["eye_of_winter_damage_+%_final_per_ground_effect_type"]=1,
	parent="skill_stat_descriptions"
}