-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Fire Resistance granted {0}%"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="Allies gain {0}% additional Fire Resistance"
			}
		},
		stats={
			[1]="skill_granted_fire_damage_resistance_%"
		}
	},
	parent="skill_stat_descriptions",
	["skill_granted_fire_damage_resistance_%"]=1
}