-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Bolts granted on kill {0}"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Lightning Bolts strike the targets of your next {0} Attack Hits\nafter Killing a Shocked Enemy with Attack Damage"
			}
		},
		stats={
			[1]="herald_of_thunder_storm_max_hits"
		}
	},
	["herald_of_thunder_storm_max_hits"]=1,
	parent="skill_stat_descriptions"
}