-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	["active_skill_base_area_of_effect_radius"]=1,
	parent="skill_stat_descriptions"
}