-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Leeches {0} Mana"
			}
		},
		stats={
			[1]="mana_drain_base_mana_leech_amount"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="Mana Leeched per cast@{0}"
			}
		},
		stats={
			[1]="mana_drain_total_mana_leech_amount"
		}
	},
	["mana_drain_base_mana_leech_amount"]=1,
	["mana_drain_total_mana_leech_amount"]=2,
	parent="skill_stat_descriptions"
}