-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="spells_have_culling_strike"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=99
					}
				},
				text="{0}% chance to grant an additional Power Charge on Cull"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]="#"
					}
				},
				text="Grants an additional Power Charge on Cull"
			}
		},
		stats={
			[1]="chance_to_gain_1_more_charge_%"
		}
	},
	["chance_to_gain_1_more_charge_%"]=2,
	parent="skill_stat_descriptions",
	["spells_have_culling_strike"]=1
}