-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="Can store up to {0} Bolts"
			}
		},
		stats={
			[1]="base_number_of_crossbow_bolts"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="number_of_crossbow_bolts"
		}
	},
	["base_number_of_crossbow_bolts"]=1,
	["number_of_crossbow_bolts"]=2,
	parent="skill_stat_descriptions"
}