-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Golden Obi"] = {
	type = "Belt",
	tags = { demigods = true, not_for_sale = true, default = true, belt = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased [ItemRarity|Rarity of Items] found",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["Rawhide Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased Life Recovery from [Flask|Flasks]",
	implicitModTypes = { { "flask", "resource", "life" }, },
	req = { },
}
itemBases["Linen Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased Mana Recovery from [Flask|Flasks]",
	implicitModTypes = { { "flask", "resource", "mana" }, },
	req = { },
}
itemBases["Wide Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased [Flask|Flask] Charges gained",
	implicitModTypes = { { "flask" }, },
	req = { level = 14, },
}
itemBases["Long Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(15-20)% increased [Charm] Effect Duration",
	implicitModTypes = { {  }, },
	req = { level = 20, },
}
itemBases["Plate Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "+(100-140) to [Armour]",
	implicitModTypes = { { "armour", "defences" }, },
	req = { level = 24, },
}
itemBases["Ornate Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(10-15)% reduced [Charm] Charges used",
	implicitModTypes = { {  }, },
	req = { level = 31, },
}
itemBases["Mail Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(10-15)% reduced [Flask|Flask] Charges used",
	implicitModTypes = { { "flask" }, },
	req = { level = 40, },
}
itemBases["Double Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased [Charm] Charges gained",
	implicitModTypes = { {  }, },
	req = { level = 44, },
}
itemBases["Heavy Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "(20-30)% increased [StunThreshold|Stun Threshold]",
	implicitModTypes = { {  }, },
	req = { level = 50, },
}
itemBases["Utility Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "20% of [Flask|Flask] Recovery applied Instantly",
	implicitModTypes = { {  }, },
	req = { level = 55, },
}
itemBases["Fine Belt"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	influenceTags = { shaper = "belt_shaper", elder = "belt_elder", adjudicator = "belt_adjudicator", basilisk = "belt_basilisk", crusader = "belt_crusader", eyrie = "belt_eyrie", cleansing = "belt_cleansing", tangle = "belt_tangle" },
	implicit = "[Flask|Flasks] gain 0.17 charges per Second",
	implicitModTypes = { {  }, },
	req = { level = 62, },
}
