-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Golden Flame"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { not_for_sale = true, demigods = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicit = "+(11-19)% to [Resistances|Chaos Resistance]",
	implicitModTypes = { { "chaos", "resistance" }, },
	armour = { BlockChance = 25, },
	req = { level = 15, },
}
itemBases["Splintered Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, ezomyte_basetype = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 18, MovementPenalty = 300, },
	req = { },
}
itemBases["Painted Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, ezomyte_basetype = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 29, MovementPenalty = 300, },
	req = { level = 6, },
}
itemBases["Braced Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, ezomyte_basetype = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 41, MovementPenalty = 300, },
	req = { level = 12, },
}
itemBases["Barricade Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 50, MovementPenalty = 300, },
	req = { level = 16, },
}
itemBases["Effigial Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 60, MovementPenalty = 300, },
	req = { level = 21, },
}
itemBases["Rampart Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 75, MovementPenalty = 300, },
	req = { level = 28, },
}
itemBases["Heraldric Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, vaal_basetype = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 85, MovementPenalty = 300, },
	req = { level = 33, },
}
itemBases["Stone Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, vaal_basetype = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 91, MovementPenalty = 300, },
	req = { level = 36, },
}
itemBases["Crucible Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 110, MovementPenalty = 300, },
	req = { level = 45, },
}
itemBases["Ancestor Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 121, MovementPenalty = 300, },
	req = { level = 50, },
}
itemBases["Phalanx Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 125, MovementPenalty = 300, },
	req = { level = 52, },
}
itemBases["Defiant Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 137, MovementPenalty = 300, },
	req = { level = 58, },
}
itemBases["Blacksteel Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 152, MovementPenalty = 300, },
	req = { level = 65, },
}
itemBases["Hardwood Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, ezomyte_basetype = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 10, Evasion = 7, MovementPenalty = 150, },
	req = { },
}
itemBases["Pelage Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, ezomyte_basetype = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 18, Evasion = 14, MovementPenalty = 150, },
	req = { level = 8, },
}
itemBases["Studded Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 27, Evasion = 23, MovementPenalty = 150, },
	req = { level = 16, },
}
itemBases["Crescent Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 39, Evasion = 34, MovementPenalty = 150, },
	req = { level = 26, },
}
itemBases["Chiseled Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, vaal_basetype = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 47, Evasion = 41, MovementPenalty = 150, },
	req = { level = 33, },
}
itemBases["Feathered Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, vaal_basetype = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 51, Evasion = 46, MovementPenalty = 150, },
	req = { level = 37, },
}
itemBases["Stratified Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 61, Evasion = 54, MovementPenalty = 150, },
	req = { level = 45, },
}
itemBases["Carved Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 63, Evasion = 57, MovementPenalty = 150, },
	req = { level = 47, },
}
itemBases["Mosaic Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 69, Evasion = 62, MovementPenalty = 150, },
	req = { level = 52, },
}
itemBases["Aureate Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 74, Evasion = 68, MovementPenalty = 150, },
	req = { level = 57, },
}
itemBases["Grand Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 84, Evasion = 76, MovementPenalty = 150, },
	req = { level = 65, },
}
itemBases["Blazon Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, ezomyte_basetype = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 10, EnergyShield = 6, MovementPenalty = 150, },
	req = { },
}
itemBases["Sigil Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, ezomyte_basetype = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 17, EnergyShield = 8, MovementPenalty = 150, },
	req = { level = 7, },
}
itemBases["Emblem Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 27, EnergyShield = 12, MovementPenalty = 150, },
	req = { level = 16, },
}
itemBases["Jingling Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 41, EnergyShield = 16, MovementPenalty = 150, },
	req = { level = 28, },
}
itemBases["Sectarian Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, vaal_basetype = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 47, EnergyShield = 18, MovementPenalty = 150, },
	req = { level = 33, },
}
itemBases["Omen Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, vaal_basetype = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 50, EnergyShield = 19, MovementPenalty = 150, },
	req = { level = 36, },
}
itemBases["Wayward Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 61, EnergyShield = 22, MovementPenalty = 150, },
	req = { level = 45, },
}
itemBases["Seer Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 65, EnergyShield = 23, MovementPenalty = 150, },
	req = { level = 49, },
}
itemBases["Stoic Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 69, EnergyShield = 24, MovementPenalty = 150, },
	req = { level = 52, },
}
itemBases["Empyreal Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 74, EnergyShield = 26, MovementPenalty = 150, },
	req = { level = 57, },
}
itemBases["Deified Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 84, EnergyShield = 29, MovementPenalty = 150, },
	req = { level = 65, },
}
itemBases["Leather Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, ezomyte_basetype = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 12, },
	req = { },
}
itemBases["Wooden Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, ezomyte_basetype = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 20, },
	req = { level = 5, },
}
itemBases["Plated Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, ezomyte_basetype = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 32, },
	req = { level = 11, },
}
itemBases["Iron Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 42, },
	req = { level = 16, },
}
itemBases["Ridged Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 54, },
	req = { level = 22, },
}
itemBases["Spiked Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { maraketh_basetype = true, dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 62, },
	req = { level = 26, },
}
itemBases["Ringed Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, vaal_basetype = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 75, },
	req = { level = 33, },
}
itemBases["Edged Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, vaal_basetype = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 87, },
	req = { level = 39, },
}
itemBases["Laminate Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 99, },
	req = { level = 45, },
}
itemBases["Pearl Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 105, },
	req = { level = 48, },
}
itemBases["Ornate Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 113, },
	req = { level = 52, },
}
itemBases["Array Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 119, },
	req = { level = 55, },
}
itemBases["Aegis Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 139, },
	req = { level = 65, },
}
itemBases["Advanced Painted Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 110, MovementPenalty = 300, },
	req = { level = 45, },
}
itemBases["Advanced Braced Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 116, MovementPenalty = 300, },
	req = { level = 48, },
}
itemBases["Advanced Effigial Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 123, MovementPenalty = 300, },
	req = { level = 51, },
}
itemBases["Advanced Rampart Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 131, MovementPenalty = 300, },
	req = { level = 55, },
}
itemBases["Advanced Heraldric Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 139, MovementPenalty = 300, },
	req = { level = 59, },
}
itemBases["Advanced Stone Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 144, MovementPenalty = 300, },
	req = { level = 61, },
}
itemBases["Advanced Hardwood Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 61, Evasion = 54, MovementPenalty = 150, },
	req = { level = 45, },
}
itemBases["Advanced Pelage Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 64, Evasion = 58, MovementPenalty = 150, },
	req = { level = 48, },
}
itemBases["Advanced Studded Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 67, Evasion = 61, MovementPenalty = 150, },
	req = { level = 51, },
}
itemBases["Advanced Crescent Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 72, Evasion = 65, MovementPenalty = 150, },
	req = { level = 55, },
}
itemBases["Advanced Chiseled Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 77, Evasion = 70, MovementPenalty = 150, },
	req = { level = 59, },
}
itemBases["Advanced Feathered Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 80, Evasion = 73, MovementPenalty = 150, },
	req = { level = 62, },
}
itemBases["Advanced Blazon Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 61, EnergyShield = 22, MovementPenalty = 150, },
	req = { level = 45, },
}
itemBases["Advanced Sigil Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 64, EnergyShield = 23, MovementPenalty = 150, },
	req = { level = 48, },
}
itemBases["Advanced Emblem Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 67, EnergyShield = 24, MovementPenalty = 150, },
	req = { level = 51, },
}
itemBases["Advanced Jingling Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 72, EnergyShield = 25, MovementPenalty = 150, },
	req = { level = 55, },
}
itemBases["Advanced Sectarian Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 77, EnergyShield = 27, MovementPenalty = 150, },
	req = { level = 59, },
}
itemBases["Advanced Omen Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 80, EnergyShield = 28, MovementPenalty = 150, },
	req = { level = 62, },
}
itemBases["Advanced Wooden Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 99, },
	req = { level = 45, },
}
itemBases["Advanced Plated Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 105, },
	req = { level = 48, },
}
itemBases["Advanced Ridged Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 111, },
	req = { level = 51, },
}
itemBases["Advanced Spiked Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 119, },
	req = { level = 55, },
}
itemBases["Advanced Ringed Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 127, },
	req = { level = 59, },
}
itemBases["Advanced Edged Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 131, },
	req = { level = 61, },
}
itemBases["Expert Braced Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 152, MovementPenalty = 300, },
	req = { level = 65, },
}
itemBases["Expert Rampart Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 167, MovementPenalty = 300, },
	req = { level = 70, },
}
itemBases["Expert Stone Tower Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 26, Armour = 182, MovementPenalty = 300, },
	req = { level = 75, },
}
itemBases["Expert Pelage Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 84, Evasion = 76, MovementPenalty = 150, },
	req = { level = 65, },
}
itemBases["Expert Crescent Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 92, Evasion = 84, MovementPenalty = 150, },
	req = { level = 70, },
}
itemBases["Expert Feathered Targe"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 100, Evasion = 91, MovementPenalty = 150, },
	req = { level = 75, },
}
itemBases["Expert Sigil Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 84, EnergyShield = 29, MovementPenalty = 150, },
	req = { level = 65, },
}
itemBases["Expert Jingling Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 92, EnergyShield = 32, MovementPenalty = 150, },
	req = { level = 70, },
}
itemBases["Expert Omen Crest Shield"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 25, Armour = 100, EnergyShield = 35, MovementPenalty = 150, },
	req = { level = 75, },
}
itemBases["Expert Plated Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 139, },
	req = { level = 65, },
}
itemBases["Expert Spiked Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 152, },
	req = { level = 70, },
}
itemBases["Expert Edged Buckler"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	influenceTags = { shaper = "shield_shaper", elder = "shield_elder", adjudicator = "shield_adjudicator", basilisk = "shield_basilisk", crusader = "shield_crusader", eyrie = "shield_eyrie", cleansing = "shield_cleansing", tangle = "shield_tangle" },
	implicitModTypes = { },
	armour = { BlockChance = 24, Evasion = 166, },
	req = { level = 75, },
}
