-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Soul Core of Tacati"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Opiloti"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Jiquani"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Zalatl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Citaqualotl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Puhuarte"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Tzamoto"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Xopec"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Azcapa"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier3 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Topotante"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier1 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Quipolatl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Ticaba"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Atmohua"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Cholotl"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Soul Core of Zantipi"] = {
	type = "SoulCore",
	hidden = true,
	tags = { soul_core = true, soul_core_tier2 = true, default = true, },
	implicitModTypes = { },
	req = { },
}

itemBases["Desert Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Glacial Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Storm Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Iron Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Body Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Mind Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Rebirth Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Inspiration Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Stone Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Vision Rune"] = {
	type = "Rune",
	hidden = true,
	tags = { default = true, },
	implicitModTypes = { },
	req = { },
}
