-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["HARVEST"] = {
		"Quality does not increase Damage/1% increased Critical Hit Chance per 4% Quality",
		"Quality does not increase Damage/Grants 1% increased Accuracy per 2% Quality",
		"Quality does not increase Damage/1% increased Attack Speed per 8% Quality",
		"Quality does not increase Damage/+1 Weapon Range per 10% Quality",
		"Quality does not increase Damage/Grants 1% increased Elemental Damage per 2% Quality",
		"Quality does not increase Damage/Grants 1% increased Area of Effect per 4% Quality",
	},
}