-- This file is automatically generated, do not edit!
-- Gem data (c) Grinding Gear Games

return {
	["Metadata/Items/Gems/SkillGemEssenceDrain"] = {
		name = "Essence Drain",
		baseTypeName = "Essence Drain",
		gameId = "Metadata/Items/Gems/SkillGemEssenceDrain",
		variantId = "EssenceDrain",
		grantedEffectId = "EssenceDrainPlayer",
		tags = {
			grants_active_skill = true,
			spell = true,
			projectile = true,
			chaos = true,
			duration = true,
		},
		tagString = "[Spell], [Projectile], [Chaos], [DurationSkill|Duration]",
		reqStr = 0,
		reqDex = 0,
		reqInt = 100,
		naturalMaxLevel = 20,
	},
	["Metadata/Items/Gems/SkillGemAxeSlash"] = {
		name = "[DNT] Axe Slash",
		baseTypeName = "[DNT] Axe Slash",
		gameId = "Metadata/Items/Gems/SkillGemAxeSlash",
		variantId = "AxeSlash",
		grantedEffectId = "AxeSlashPlayer",
		tags = {
			grants_active_skill = true,
			attack = true,
			melee = true,
			strike = true,
		},
		tagString = "[Attack], [Melee], [Strike]",
		reqStr = 100,
		reqDex = 0,
		reqInt = 0,
		naturalMaxLevel = 1,
	},
}