-- This file is automatically generated, do not edit!
-- Gem data (c) Grinding Gear Games

return {
	["Metadata/Items/Gems/SkillGemArc"] = {
		name = "Arc",
		baseTypeName = "Arc",
		gameId = "Metadata/Items/Gems/SkillGemArc",
		variantId = "Arc",
		grantedEffectId = "ArcPlayer",
		tags = {
			grants_active_skill = true,
			spell = true,
			lightning = true,
			chaining = true,
		},
		tagString = "Spell, Lightning, Chaining",
		reqStr = 0,
		reqDex = 0,
		reqInt = 100,
		naturalMaxLevel = 20,
	},
	["Metadata/Items/Gems/SkillGemAncestralWarriorTotem"] = {
		name = "Ancestral Warrior Totem",
		baseTypeName = "Ancestral Warrior Totem",
		gameId = "Metadata/Items/Gems/SkillGemAncestralWarriorTotem",
		variantId = "AncestralWarriorTotem",
		grantedEffectId = "AncestralWarriorTotemPlayer",
		additionalGrantedEffectId = "SupportAncestralWarriorTotemPlayer",
		tags = {
			grants_active_skill = true,
			attack = true,
			totem = true,
			area = true,
			melee = true,
			physical = true,
			duration = true,
			meta = true,
		},
		tagString = "Attack, Totem, AoE, Melee, Physical, Duration, Meta",
		reqStr = 100,
		reqDex = 0,
		reqInt = 0,
		naturalMaxLevel = 20,
	},
}