-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Soul Core of Tacati"] = {
		weapon = { "15% chance to Poison on Hit", statOrder = { 6867 }, },
		armour = { "+7% to Chaos Resistance", statOrder = { 953 }, },
	},
	["Soul Core of Opiloti"] = {
		weapon = { "15% chance to cause Bleeding on Hit", statOrder = { 2156 }, },
		armour = { "10% increased Charm Charges gained", statOrder = { 5066 }, },
	},
	["Soul Core of Jiquani"] = {
		weapon = { "Recover 2% of Life on Kill", statOrder = { 1443 }, },
		armour = { "2% increased maximum Life", statOrder = { 872 }, },
	},
	["Soul Core of Zalatl"] = {
		weapon = { "Recover 2% of Mana on Kill", statOrder = { 1445 }, },
		armour = { "2% increased maximum Mana", statOrder = { 874 }, },
	},
	["Soul Core of Citaqualotl"] = {
		weapon = { "30% increased Elemental Damage with Attacks", statOrder = { 860 }, },
		armour = { "+5% to all Elemental Resistances", statOrder = { 949 }, },
	},
	["Soul Core of Puhuarte"] = {
		weapon = { "30% increased chance to Ignite", statOrder = { 978 }, },
		armour = { "+1% to Maximum Fire Resistance", statOrder = { 945 }, },
	},
	["Soul Core of Tzamoto"] = {
		weapon = { "20% increased Freeze Buildup", statOrder = { 980 }, },
		armour = { "+1% to Maximum Cold Resistance", statOrder = { 946 }, },
	},
	["Soul Core of Xopec"] = {
		weapon = { "30% increased chance to Shock", statOrder = { 982 }, },
		armour = { "+1% to Maximum Lightning Resistance", statOrder = { 947 }, },
	},
	["Soul Core of Azcapa"] = {
		weapon = { "+15 to Spirit", statOrder = { 876 }, },
		armour = { "10% increased Rarity of Items found", statOrder = { 911 }, },
	},
	["Soul Core of Topotante"] = {
		weapon = { "Attacks with this Weapon Penetrate 15% Elemental Resistances", statOrder = { 3369 }, },
		armour = { "15% increased Elemental Ailment Threshold", statOrder = { 4150 }, },
	},
	["Soul Core of Quipolatl"] = {
		weapon = { "5% increased Attack Speed", statOrder = { 914 }, },
		armour = { "10% reduced Slowing Potency of Debuffs on You", statOrder = { 4506 }, },
	},
	["Soul Core of Ticaba"] = {
		weapon = { "+12% to Critical Damage Bonus", statOrder = { 913 }, },
		armour = { "Hits against you have 10% reduced Critical Damage Bonus", statOrder = { 942 }, },
	},
	["Soul Core of Atmohua"] = {
		weapon = { "Convert 20% of Requirements to Strength", statOrder = { 6872 }, },
		armour = { "Convert 20% of Requirements to Strength", statOrder = { 6872 }, },
	},
	["Soul Core of Cholotl"] = {
		weapon = { "Convert 20% of Requirements to Dexterity", statOrder = { 6870 }, },
		armour = { "Convert 20% of Requirements to Dexterity", statOrder = { 6870 }, },
	},
	["Soul Core of Zantipi"] = {
		weapon = { "Convert 20% of Requirements to Intelligence", statOrder = { 6871 }, },
		armour = { "Convert 20% of Requirements to Intelligence", statOrder = { 6871 }, },
	},
	["Desert Rune"] = {
		weapon = { "Adds 7 to 11 Fire Damage", statOrder = { 824 }, },
		armour = { "+12% to Fire Resistance", statOrder = { 950 }, },
	},
	["Glacial Rune"] = {
		weapon = { "Adds 6 to 10 Cold Damage", statOrder = { 825 }, },
		armour = { "+12% to Cold Resistance", statOrder = { 951 }, },
	},
	["Storm Rune"] = {
		weapon = { "Adds 1 to 20 Lightning Damage", statOrder = { 826 }, },
		armour = { "+12% to Lightning Resistance", statOrder = { 952 }, },
	},
	["Iron Rune"] = {
		weapon = { "20% increased Physical Damage", statOrder = { 822 }, },
		armour = { "20% increased Armour, Evasion and Energy Shield", statOrder = { 1370 }, },
	},
	["Body Rune"] = {
		weapon = { "Leeches 3% of Physical Damage as Life", statOrder = { 961 }, },
		armour = { "+25 to maximum Life", statOrder = { 871 }, },
	},
	["Mind Rune"] = {
		weapon = { "Leeches 2% of Physical Damage as Mana", statOrder = { 967 }, },
		armour = { "+20 to maximum Mana", statOrder = { 873 }, },
	},
	["Rebirth Rune"] = {
		weapon = { "Gain 20 Life per Enemy Killed", statOrder = { 964 }, },
		armour = { "Regenerate 0.3% of Life per second", statOrder = { 1627 }, },
	},
	["Inspiration Rune"] = {
		weapon = { "Gain 10 Mana per Enemy Killed", statOrder = { 969 }, },
		armour = { "15% increased Mana Regeneration Rate", statOrder = { 965 }, },
	},
	["Stone Rune"] = {
		weapon = { "Causes 25% increased Stun Buildup", statOrder = { 974 }, },
		armour = { "+40 to Stun Threshold", statOrder = { 984 }, },
	},
	["Vision Rune"] = {
		weapon = { "+100 to Accuracy Rating", statOrder = { 827 }, },
		armour = { "10% increased Life and Mana Recovery from Flasks", statOrder = { 5906 }, },
	},
}